### ISSUE TITLE
Clarify the relationship to the Forth programming language

### ISSUE THREAD

**Issue by marksmith** [ampleforth/Forth#3]
As a member of the Forth community, a programmer who has worked and continues to work in the [Forth](https://en.wikipedia.org/wiki/Forth_(programming_language)) programming language and the author of an open-source Forth implementation ([Able Forth](https://github.com/ablevm/able-forth)), I must admit that I am confused by your use of the term Forth.

Please could you clarify what relationship exists (if any) between your "Forth" and the well-known Forth programming language? Why was the name Forth chosen?

If there is no relationship between Ampleforth and the Forth programming language then the cooption of the long-established term Forth is a recipe for disaster for both our respective communities.

Thanks in advance,

Mark

**Comment by brandoniles** [comment]
Hey Mark,
Thanks for voicing the concern. As you suspect, there's no relationship between the governance token of the Ampleforth protocol and the Forth programming language. I think there's enough precedent that digital currencies and languages are sufficiently different to avoid confusion. For example, the [#3 currency ADA](https://www.coingecko.com/en/coins/cardano). Since launch, we haven't notice any confusion between these within any of our channels or communities.
